language: java

jdk:
  - oraclejdk7
  - oraclejdk8

before_install:
  - chmod +x ./.travis/maven-build.sh
  - chmod +x ./.travis/call-creation.sh
  - mvn clean

install:
  - sudo apt-get update && sudo apt-get --assume-yes install zip unzip

script: "./.travis/maven-build.sh"

after_deploy: "./.travis/call-creation.sh"

notifications:
  email: false
  slack:
    secure: osWX769z0hSVPbeF1ZHSENgR4i+VKFTMGFNIV02RhvZ4a1BXsGUG5VCCDYUoBzWPCA5avJHg+FrN7nEEaoIjc5/qqFmZFGwOitZJsOzvR8C18QcgyuEX+35U4eQF4h5ITpruvwNNQ/7hIWyPl/fEPcAswHFDAccEb5iRNJeFNeM=
  webhooks:
    on_success: always
    on_failure: always
    on_start: never

env:
  global:
    - PROVIDER_VERSION=1.0

cache:
  directories:
    - ".autoconf"
    - "$HOME/.m2"

deploy:
  - provider: s3
    access_key_id: AKIAJDZLZNH2PIKHUKOA
    secret_access_key:
      secure: LcS1dq0MtW4VIczNe4tGkxTPSg2DBDydBOO98hUhDG+/BdQ3GUTX77jyyG6IL2hqqM5/diInw71qZdYWyAJIMAu0uSA7SrTp/yzBhJFCegquAqbBXbSLFqV9IvyDX22nloUsH7/ZZGFfEZ7T+EjuF+9UYBITgeuohWlKiEWbuUJmECmvx7syG/H7G/tWs89vcyRXjn0cGIw1h+r3dGtSCLt0W2B7vo8SvSH8LpMS49sgpNsEahvS3wgWhXXX+tEwiclngef46MBYcnyrtDHwQM5C83Qq9iYITEZTGHCibTy1T7BlnMqDlwCgHCYB3EDhft+gWppKnSRFZi9mCelbJVXozmjvPybA0W3mjzntszgvAQ5t26L214S7yNZpfaUltB9XW2D94p+y6QmWldMyIaEfswmGAs+h52Gp3dnovVOsS7e515NUvWoFFnH7mmPhAcnxUjnOTw9jJ2HUnVS72Bi+cCMo+RPGP9tNoNaKGxXSqRvG7E5UGyaPvOh2J4ogmrBqrnrK5cB/ho6+gNNu0YirwJzzujgln4kPxjZU1R0TpiAhiadfWytPduilY6r2BA94UwnZEsRUNvsJFOI/eyWa2E+RdDi0fvDg5nUxWoi2Nr+jOXyMab8vS+AzNWI6Khp1pA6M7dnwmfwCSlFHgLLhxNvt8O8JzckP+JtqkRA=
    bucket: parabot
    skip_cleanup: true
    local-dir: "./target/final/"
    upload-dir: artifacts/soulplay-provider
    region: us-west-1
    detect_encoding: true
    acl: public_read
    on:
      repo: Parabot/Parabot-317-API-Minified-SoulPlay
      branch:
        - master
        - development
      jdk: 'openjdk7'
