language: java

jdk:
  - oraclejdk7
  - oraclejdk8

before_install:
  - chmod +x ./.travis/maven-build.sh
  - chmod +x ./.travis/call-creation.sh
  - mvn clean

install:
  - sudo apt-get update && sudo apt-get --assume-yes install zip unzip

script: "./.travis/maven-build.sh"

after_deploy: "./.travis/call-creation.sh"

notifications:
  email: false
  slack:
    secure: osWX769z0hSVPbeF1ZHSENgR4i+VKFTMGFNIV02RhvZ4a1BXsGUG5VCCDYUoBzWPCA5avJHg+FrN7nEEaoIjc5/qqFmZFGwOitZJsOzvR8C18QcgyuEX+35U4eQF4h5ITpruvwNNQ/7hIWyPl/fEPcAswHFDAccEb5iRNJeFNeM=
  webhooks:
    on_success: always
    on_failure: always
    on_start: never

env:
  global:
    - PROVIDER_VERSION=1.0

cache:
  directories:
    - ".autoconf"
    - "$HOME/.m2"

deploy:
  - provider: s3
    access_key_id: AKIAJDZLZNH2PIKHUKOA
    secret_access_key:
      secure: aGFNOrQ/VZScEqGcRr7NOP1CP9etGbAUvesgpoTVDiT59PknJKdCo7TDDzAfKlBHcHxuiBNaHkkmuj6pRkWff3Ffsb00VP6k04LGu+strzWThk1woTYx+3I7bcEa1U45Gfo/Y6xtOI1gSE3IHLeOX80ebfioR7jrKBtmE5pgbOG0jySco7KIftmct72zsHG/Ema8rmQEVpPxKh0FLRcddQIJ3i6/1DdRYkCtjqL5m9B4igIeio9qw8GiiM1pG/RCn3VX/MOKGa675q/U9x0G8Oc36EaEKTW0Vws3yVxZiKSBBT5akmeUwzODRBGA5z/9s23XQJmjDOnTjX/M7v8AKwkVfsti98lxBmfHeGxVJSI2ofx25Re8yjkPX6u+tRrN8L4W5NVc5qYPJwldYzXuYGMfuPKpwD5EDloM+PkSAMA56YxA+0VOZRxyFA0wvc+CoacIKPHSVBXz8dU3WhtCfhBdDt+XXsq0U2rBa5jqqYGxNoN74EyU+C2mXpPP7nsVfbeOO1FohJgWeH3pa4K0xOjg4HY7rIcrwvPjCArDRh/AXIWQzXnhRRtcHdG37pTsfP0SGL8QX4SutFFpvfgqwbkEkKuIpkt1cLaD3tgLSfUp4xmSA2Jef0bP3OKEpK6+JUyniWxXuw23boAODKfy4WmhdUpfiIKJTu7VBq6lAMU=
    bucket: parabot
    skip_cleanup: true
    local-dir: "./target/final/"
    upload-dir: artifacts/soulplay-provider
    region: us-west-1
    detect_encoding: true
    acl: public_read
    on:
      repo: Parabot/Parabot-317-API-Minified-SoulPlay
      branch:
        - master
        - development
      jdk: 'openjdk7'
